### ISSUE TITLE
[Feature]: ArtworRecordView가 load될 때 사용자가 리뷰한 Artwork와 QuestionAnswer을 DB에서 불러온다.

### ISSUE THREAD

**Issue by rriver2** [DeveloperAcademy-POSTECH/MacC_Team_Beartear#112]
### Feature 설명
<img width="910" alt="스크린샷 2022-11-24 오후 2 27 18" src="https://user-images.githubusercontent.com/82457928/203701358-970f6ba5-4099-428f-924d-5426fbe6687b.png">

- [x] ArtworRecordViewModel 구현

요구사항 )
- ArtworRecordView가 load될 때 사용자가 리뷰한 Artwork와 QuestionAnswer을 DB에서 불러온다.
- 둘 중 하나라도 실패하면 실패로 취급
- 둘 다 load 완료시에 성공

### Prepare Issue(Optional)

#111, #87

**Comment by HoJongE** [comment]
이 이슈 관련해서 뭔가 조언해주고 싶은게 있어요. 다들 들었으면 좋곘네요.
