### ISSUE TITLE
[Refactor]: HighlightTextView를 MyFeedView에 적용합니다.

### ISSUE THREAD

**Issue by imparang** [DeveloperAcademy-POSTECH/MacC_Team_Beartear#113]
### Refactoring 설명

- 호종이가 만든 HighlightTextView를 MyFeedView에 적용하여 리팩토링 합니다.

**Comment by HoJongE** [comment]
혹시 작업 중이신가요!? 

HighlightTextView의 layout을 수정해서, 최신 develop 에서 리팩토링 작업을 진행하시면 좋을 것 같아요!

@imparang

**Comment by imparang** [comment]
oh no
