### ISSUE TITLE
[refactor]: ReviewedArtworkUsecase와 Repository, QuestionAnswerUsecase와 Repository의 파라매터에서 UserId 삭제

### ISSUE THREAD

**Issue by rriver2** [DeveloperAcademy-POSTECH/MacC_Team_Beartear#117]
### Refactoring 설명

<img width="838" alt="스크린샷 2022-11-26 오후 7 07 26" src="https://user-images.githubusercontent.com/82457928/204083312-77f14935-bbd8-40b4-89f4-1071d0cb25b9.png">
현재 이런식으로 파라매터 값으로 받는데, 생각해보니까 UserViewModel를 singleton으로 구현해서 파라매터를 받지 않고 
함수 내부에서 UserViewModel.shared에 접근하면 될 것 같다는 생각을 했습니다. 

그래서 ReviewedArtworkUsecase와 Repository, QuestionAnswerUsecase와 Repository의 파라매터에서 UserId 삭제하려 합니다.

**Comment by HoJongE** [comment]
아니요 하지마세요 놔두세요

**Comment by HoJongE** [comment]
싱글톤에 되도록 의존하지 않는게 좋습니다. 그리고 데이터 레이어에서 presenter 레이어를 의존하는건 좋지 않아요

**Comment by rriver2** [comment]
넵 확인했습니다 ~ ㅎㅎ

**Comment by HoJongE** [comment]
함수 내부에서, 함수 외부의 상태에 의존하는 것은 좋지 않아요. 나중에 repository 나 usecase를 사용하는 클라이언트를 테스트한다고 했을 때, repository가 우선 외부의 상태(싱글톤)에 의존하기 때문에 원하는대로 행동을 조절하기 어렵습니다. 만약 6번 이전의 작품들을 불러온다는 테스트를 작성할 때, 먼저 Singleton인 뷰모델의 User 프로퍼티를 변경한 후에 repository를 테스트해야겠죠. 
이런 행동들은 당장 내가 개발할 때는 편할 수 있으나, 나중에 다른 개발자가 이것을 테스트하려고 할 때, 이 함수가 도대체 어떤 정보를 보고 artwork들을 불러오는 건지 확인을 해야 하구요. 결과적으론 협업 시 굉장히 많은 버그를 낳을 수 있어요.
하지만 지금처럼 매개변수를 받으면, 이 함수가 어떤 정보들을 가지고 동작하는지 확실히 알 수 있겠죠.
