### ISSUE TITLE
[Feature]: DB에서 데이터를 불러오는데 실패했을 때, ErrorView를 보여줍니다.

### ISSUE THREAD

**Issue by imparang** [DeveloperAcademy-POSTECH/MacC_Team_Beartear#123]
### Feature 설명

<img width="962" alt="Screenshot 2022-11-27 at 13 14 44" src="https://user-images.githubusercontent.com/59136391/204118917-ec815650-efb0-40ca-8689-2edaa2fe2c3a.png">

디자인 시안을 보면 EmptyView를 기점으로, 데이터를 불러왔을 때 보여지는 뷰를 ErrorView로 지칭했습니다.
해당 ErrorView는 여러 케이스에서 사용되기 때문에 공용 Component로 만들고자 합니다.

- [ ] DB에서 데이터를 불러오는데 실패했을 때, ErrorView를 보여줍니다.

### Related View(Optional)

[라인의 디자인 시스템](https://designsystem.line.me/LDSM/components/empty-ex-ko)

**Comment by HoJongE** [comment]
좋군요! 에러 뷰 컴포넌트에 retry button click closure만 넘길 수 있으면 좋을 것 같네요!!
