### ISSUE TITLE
[Feature]: 작품 기록 화면에서 데이터 요청 결과에 따른 UI를 구현하겠습니다.

### ISSUE THREAD

**Issue by imparang** [DeveloperAcademy-POSTECH/MacC_Team_Beartear#125]
### Feature 설명
<img width="166" alt="Screenshot 2022-11-28 at 13 59 50" src="https://user-images.githubusercontent.com/59136391/204197480-954e237f-7f14-44b7-8a19-ac215d37747b.png">

- [ ] DB에 데이터를 요청하여 성공했을 때 UI 구현
- [ ] DB에 데이터를 요청하여 실패했을 때 UI 구현

**Comment by HoJongE** [comment]
이슈 작성할 때 되도록이면 스크린샷도 붙여주세요. 무슨 데이터 요청 결과에 따른 UI를 구현하겠다는건가요?
