### ISSUE TITLE
[Feature]: Loading시 보여주는 TempSkeletonImageViewController 구현

### ISSUE THREAD

**Issue by rriver2** [DeveloperAcademy-POSTECH/MacC_Team_Beartear#173]
### Feature 설명

원래라면, 코드로 Skeleton View를 구현해야 하지만.. 시간이 없어서 우선 image로 TempSkeletonImageViewController를 구현하려 합니다..

**Comment by HoJongE** [comment]
ViewController말고, UIView를 그냥 MainViewController 위에 추가하는 방식으로 가는게 더 간단할 것 같아요!

**Comment by rriver2** [comment]
@HoJongE 앗 코멘트를 해당 내용 구현 다 하고 PR 올리기 전에 확인했어요 ! PR 보시고 말씀해주신 부분이 더 나을 것 같다면 다시 말씀 부탁드려요 ..!
