### ISSUE TITLE
[Feature]: 사용자가 작성한 작품에 대한 리뷰가 없을 때 보여주는 UI 구현

### ISSUE THREAD

**Issue by rriver2** [DeveloperAcademy-POSTECH/MacC_Team_Beartear#177]
### Feature 설명

ReviewedArtworkList가 emty일 때, 
사용자에게 아직 작성한 작품이 없다는 것을 명시하는 UI 구현
<img width="245" alt="스크린샷 2022-12-02 오후 10 54 04" src="https://user-images.githubusercontent.com/82457928/205308445-51ef75d6-aa6a-4472-b7b3-3a2da3a057bd.png">

**Comment by rriver2** [comment]
<img width="232" alt="스크린샷 2022-12-04 오후 12 20 41" src="https://user-images.githubusercontent.com/82457928/205472652-cd346b72-1410-4f18-8ab3-06802c6b1fb8.png">
@imparang 
여기 리로드 대신에 "첫 작품 감상하러 가기" 버튼이 필요한데.. 커스텀 가능할까요 ? 바쁘시면 제가.. 해보겠습니다...! 
급한 대로 retryButton을 없앨 수 있게 하는 것도 괜찮을 거 같아요.

**Comment by imparang** [comment]
> <img alt="스크린샷 2022-12-04 오후 12 20 41" width="232" src="https://user-images.githubusercontent.com/82457928/205472652-cd346b72-1410-4f18-8ab3-06802c6b1fb8.png">
> 
> @imparang 여기 리로드 대신에 "첫 작품 감상하러 가기" 버튼이 필요한데.. 커스텀 가능할까요 ? 급한 대로 retryButton을 없앨 수 있게 하는 것도 괜찮을 거 같아요. 호옥시이.. 바쁘시다면 제가.. 해보겠습니다...!

제가 할게요.
일단 retryButton으로 놔두고 작업하시면 제가 적용시킬게요.
