### ISSUE TITLE
[Feature]: 리뷰된 작품을 불러오는 거를 실패했을 때 보여주는 UI 추가

### ISSUE THREAD

**Issue by rriver2** [DeveloperAcademy-POSTECH/MacC_Team_Beartear#178]
### Feature 설명

<img width="266" alt="스크린샷 2022-12-02 오후 10 54 55" src="https://user-images.githubusercontent.com/82457928/205308618-4c697a03-33ae-4af6-85c5-ecc7fde5e5dd.png">
이미 구현되어 있는 ErrorView를 사용해서 리뷰된 작품을 불러오는 것을 실패했을 때 보여주는 View를 구현합니다.

**Comment by SH0123** [comment]
해당 UI는 https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/124 여기서 구현이 되어 있기 때문에 사용만 하시면 될 것 같습니다
@rriver2
