### ISSUE TITLE
[Feature]: MainView loading 화면 구현하기

### ISSUE THREAD

**Issue by rriver2** [DeveloperAcademy-POSTECH/MacC_Team_Beartear#179]
### Feature 설명

MainView의 오늘의 티라미술 작품과 리뷰한 작품들 list를 불러오는 요청이 모두 끝나기 전 보여줄 loading 화면 구현하기
<img width="174" alt="스크린샷 2022-12-02 오후 11 08 01" src="https://user-images.githubusercontent.com/82457928/205311138-02ece4b9-9e65-4514-b7f5-53884585770e.png">

@HoJongE 호종이에게 전에 @SH0123 랑 같이 물어본 적이 있었는데, 혹시 이 task 호종이가 가져가 주실 수 있나요 ?

**Comment by HoJongE** [comment]
오키 제가 가져가겠습니다 그러면
