### ISSUE TITLE
[Feature]: Tuist 도입하고 싶습니다.

### ISSUE THREAD

**Issue by HoJongE** [DeveloperAcademy-POSTECH/MacC_Team_Beartear#40]
### Feature 설명

Swift 코드로 프로젝트를 생성할 수 있는 Tuist 를 도입하고 싶습니다.

이유: pbxproj 충돌이 너무 많이 일어남... 프로젝트 규모가 적은 지금이야 수동으로 해결할 수 있지만, 만약 규모가 계속해서 커진다면?? swift 파일로 프로젝트를 관리할 수 있는 (충돌을 쉽게 해결할 수 있는) Tuist 가 제격이라고 생각합니다. 규모가 커지기 전 지금 단계에서 도입해야 좋을 것 같군요. 마침 사용도 쉽다고 하니 한 번 공부해보고 공유해보겠습니다.

https://docs.tuist.io/building-at-scale/microfeatures

**Comment by imparang** [comment]
모듈화 적용시 기대되는 효과
- 코드 안정성
  - 모듈간 결합도가 낮아지고 응집도가 높아지는 만큼 안정성이 높아지길 기대합니다.
  - 문제 발생시 분석이 수월해질 것으로 예상합니다.
- 개발 생산성
  - 모듈별 의존성이 낮아지면 고려해야 하는 범위가 낮아져 개발 속도가 향상됩니다.
  - 코드 리뷰시 관련 모듈만 검토가 가능해 리뷰어에게 편의가 높아질 것입니다.
- 빌드 속도
  - 자주 변경되지 않는 모듈의 빌드가 발생하지 않아 빌드 속도에도 작은 영향을 줄 것 입니다
- 사용 목적에 맞는 코드 배치
  - 용도와 목적에 맞는 코드 배치로 이해하기 쉬운 프로젝트 구성이 될 것입니다.
