### ISSUE TITLE
[refactor]: LoginManagerProtocol 구현

### ISSUE THREAD

**Issue by rriver2** [DeveloperAcademy-POSTECH/MacC_Team_Beartear#42]
### Refactoring 설명

<img width="706" alt="스크린샷 2022-11-02 오후 3 42 45" src="https://user-images.githubusercontent.com/82457928/199418752-1888b0f6-4c73-42ea-9663-2aef7ed21d99.png">

LoginManagerProtocol 상효보이와 같이 구현합니다..! (의논후에 issue 상세 설명 추가하겠습니다)

**Comment by imparang** [comment]
refactor -> Refactor로 고쳐주세요
