### ISSUE TITLE
[Feature]: OnBoarding 분기

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MacC_Team_Beartear#47]
### 작업 내용
sceneDelegate에서 분기 처리를 진행하려 합니다.
onBoarding용 NavigationController와 main용 NavigationController를 구분하여 구현합니다.

### 변수 사용
User정보를 받아와서 user가 있는 경우 mainViewController를, user가 없는 경우 onBoardingViewController를 보여줍니다.

수도코드
```swift
rootViewController = User ? mainViewController() : onBoardingViewController()
```

### 고민 사항
onBoardingViewController의 마지막 view에서 확인 버튼을 눌렀을 때 rootViewController를 mainViewController로 전환해야합니다.
isOnboardingChecked 변수를 observable sequence로 만들어서 관찰하고, 값이 바뀌면 mainViewController로 전환 되도록 해야하나요?
아니면 굳이 sequence를 만들 필요가 없다면 delegate 패턴을 사용하면 될까요?
조언 부탁드립니다 ~!

**Comment by rriver2** [comment]
### 고민 사항 의견 )
저는 굳이 sequence를 만들어야 할까..? 싶습니다 !

### 질문 )
isOnboardingChecked을 확인하는 방법은 유저의 디바이스 고유 넘버가 파베에 User id 값이 있냐 없냐로 판단되는 건가요 ?

**Comment by HoJongE** [comment]
온보딩에서 완료화면을 누르면, User정보가 db에 등록되고, 또한 User정보가 db에 등록되있으면 Onboarding을 스킵하면 될 것 같아요. 
따라서 앱을 켰을 떄, User가 db에 있는지를 확인하고, 없으면 온보딩 보여주면 될 것 같습니다.

**Comment by SH0123** [comment]
얘기 나눈대로 구현하겠습니다
