### ISSUE TITLE
[Feature]: SceneDelegate에서 User 정보를 DB에서 불러오는 Viewmodel 구현

### ISSUE THREAD

**Issue by rriver2** [DeveloperAcademy-POSTECH/MacC_Team_Beartear#94]
### Feature 설명
- [x] UserViewModel Singleton으로 구현
- [x] FetchUserUsecase protocol 정의
- [x] RealFetchUserUsecase 구현

<img width="1416" alt="스크린샷 2022-11-23 오후 4 37 44" src="https://user-images.githubusercontent.com/82457928/203493533-23df90e3-95a2-41dc-801e-c5ab077de7b6.png">

- User 정보를 DB에서 불러오는 UserViewmodel을 Singleton으로 구현
: Singleton으로 구현하는 것에 대한 고민 : [discussion](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/discussions/92#discussion-4591988)

### 참고 문헌
class diagram 그리면서 기초가 많이 부족한 거 같아서 🥲, UML class diagram을 공부하고 [블로그](https://rriver2.tistory.com/entry/UML-Diagram-%EC%9D%B4%EB%9E%80)에 글 올렸습니다. 
[Clean Architecture - UseCase 란 ?](https://heegs.tistory.com/58)

### Prepare Issue(Optional)

[#74](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/issues/74)

**Comment by HoJongE** [comment]
우리팀 코드 수준이 높군요
